<?php
namespace MeadSteve\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-30 at 18:34:19.
 */

include_once __DIR__ . "/bootstrap.php";

class SingletonTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Singleton
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Singleton(
			function(Container $Cont = null) {
				return new \stdClass();
			}
		);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MeadSteve\Container\Singleton::GetInstance
     */
    public function testGetInstance()
    {
		$FirstReturned = $this->object->GetInstance();
        $SecondReturned = $this->object->GetInstance();
		$this->assertEquals($FirstReturned, $FirstReturned);
    }

    /**
     * @covers MeadSteve\Container\Singleton::__invoke
     */
    public function test__invoke()
    {
		$Callable = $this->object;
    	$FirstReturned = $Callable();
        $SecondReturned = $Callable();
		$this->assertEquals($FirstReturned, $FirstReturned);
	}
}
